### ISSUE TITLE
[Bug]: Some html tags not supported

### ISSUE THREAD

**Issue by mcp1766** [Bekaboo/dropbar.nvim#180] opened 2024-08-27 21:47 UTC
### Description

Some html tags are not displayed in the dropbar in the way that we expected (see pictures)

![Capture d’écran du 2024-08-27 23-38-53](https://github.com/user-attachments/assets/070981c6-d33f-4af4-be44-8752749b8199)

Passing over **html**,  **head** tags are well displayed on the dropbar and their respective position is correct but **body** not.

![Capture d’écran du 2024-08-28 05-58-25](https://github.com/user-attachments/assets/e42b29e6-4c92-415a-a89b-a051aa774a72)

The **body** tag and its children are included within the **head** tag ; what is not correct in my opinion as **body** tag is not a child of **head** tag.
### nvim version

0.10.1

### dropbar.nvim version

6156e07

### Operating system and version

Pop OS 22.04 LTS

### Minimal config

```Lua
return
  {
    'Bekaboo/dropbar.nvim',
    -- optional, but required for fuzzy finder support
    dependencies = {
      'nvim-telescope/telescope-fzf-native.nvim'
    }
  }
```

### Steps to reproduce

Saved dropbar.lua
Restarted Nvim
Opened a html file

### Expected behavior

Expected to see all html tags in the correct order in the dropbar

### Actual behavior

Dropbar does not show <body> tag as a child of <html> but as a child of <head> tag.

### Additional information

No addition

**Comment by Bekaboo** [comment] 2024-08-28 18:21
Hi thanks for reporting the issue. Please provide the example html so that track the bug.

**Comment by Bekaboo** [comment] 2024-09-25 04:40
Closing, cannot reproduce.

**Closed by Bekaboo** 2024-09-25 04:40 UTC
Labels: bug

**Comment by frogpal** [comment] 2025-06-14 21:54
Hi, I know this issue was already closed, but I am also experiencing the same problem (check screenshot).

![Image](https://github.com/user-attachments/assets/20cf037a-075a-4640-aae4-5bc9b12d26be) 

But everything inside the `<head>` tag is shown as expected, just like @mcp1766 mentioned.

![Image](https://github.com/user-attachments/assets/ec6bd776-414b-4a63-8033-338463eccfb5)

This is the example html in the screenshot:

```
<!doctype html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <!--<meta charset="UTF-8">-->
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Test title</title>
        <link href="css/style.css" rel="stylesheet" />
    </head>
    <body>
        <div>This is some text</div>
        <div>This is some text</div>
        <div>This is some text</div>
        <p>This is a paragraph</p>
        <div>stuff</div>
        <main>
            <header></header>
        </main>
    </body>
</html>
```

I have both an LSP and treesitter installed. Do you know what the issue could be? Thanks for any help!

**Comment by kulothunganug** [comment] 2026-04-14 03:47
elements inside head works fine
<img width="1083" height="484" alt="Image" src="https://github.com/user-attachments/assets/b3720eeb-be29-4180-a910-53fddf6c1134" />

elements below head is not (body not showing up)

<img width="1083" height="484" alt="Image" src="https://github.com/user-attachments/assets/5c76df1d-ddb6-4610-9076-9c2269ae8489" />

if i remove head tag, body shows fine

<img width="1083" height="484" alt="Image" src="https://github.com/user-attachments/assets/6d6b381f-cca2-464f-b62c-f472c8665cf7" />

code used
```html
<!DOCTYPE >
<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title></title>
    <link href="css/style.css" rel="stylesheet" />
  </head>
  <body>
    <div>
      <p>Hello</p>
    </div>
  </body>
</html>

```

please reopen the issue
