### ISSUE TITLE
[Bug]: Dropbar throws an error when opening files that don't have a "client" associated with them

### ISSUE THREAD

**Issue by miversen33** [Bekaboo/dropbar.nvim#103] opened 2023-10-13 03:36 UTC
### Description

I discovered this issue when I accidentally opened a `.png` file earlier. Dropbar tosses this nice error
```vim
Error executing vim.schedule lua callback: ...share/nvim/lazy/dropbar.nvim/lua/dropbar/sources/lsp.lua:339: attempt to call field 'get_clients' (a nil value)
stack traceback:
        ...share/nvim/lazy/dropbar.nvim/lua/dropbar/sources/lsp.lua:339: in function 'init'
        ...share/nvim/lazy/dropbar.nvim/lua/dropbar/sources/lsp.lua:382: in function 'get_symbols'
        ...hare/nvim/lazy/dropbar.nvim/lua/dropbar/utils/source.lua:9: in function 'get_symbols'
        .../.local/share/nvim/lazy/dropbar.nvim/lua/dropbar/bar.lua:526: in function ''
        vim/_editor.lua: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>
```

Indeed a `.png` file does not have a client (not LSP, treesitter, etc) but I wouldn't imagine that should matter. What is weird is not _every_ file that has no client associated with them toss this error. For example, I opened a gzipped tar (tar.gz) and dropbar didn't have any issue. However, opening a `LICENSE` in another project does throw this error.

I suspect there is an issue in not checking if any clients are available before fetching it.

What's most interesting is dropbar gracefully recovers. It will be visible in other files and I can even close the problem buffer and open the problem file again and Dropbar doesn't have any issues with it. So maybe its related to opening a file that has no LSP before dropbar has been able to establish clients in general? Not really sure

### nvim version

NVIM v0.10.0-dev-585+g2e055e49a

### dropbar.nvim version

79309dc

### Operating system and version

Arch Linux

### Minimal config

```Lua
local tmp = vim.env.TMPDIR
  or vim.env.TEMPDIR
  or vim.env.TMP
  or vim.env.TEMP
  or '/tmp'
local data = tmp ..  '/' .. (vim.env.NVIM_APPNAME or 'nvim')
local packages_root = data .. '/site'
local cloned_root = packages_root .. '/pack/packages/start'
local cloned_path = cloned_root .. '/dropbar.nvim'
local url = 'https://github.com/Bekaboo/dropbar.nvim.git'

vim.fn.mkdir(cloned_root, 'p')
vim.opt.pp:prepend(packages_root)
vim.opt.rtp:prepend(packages_root)

if not vim.loop.fs_stat(cloned_path) then
  vim.fn.system({ 'git', 'clone', url, cloned_path })
end

require('dropbar').setup()
```

### Steps to reproduce

Open a file that you know for sure has no LSP associated with it. That seems to be the only thing I need to do

### Expected behavior

If Dropbar cannot find a client, it shouldn't attempt to fetch one (and thus avoid dumping icky red text on my screen :) )

### Actual behavior

Icky red text make work stop

**Comment by Bekaboo** [comment] 2023-10-13 03:57
@miversen33 Interesting, but I was not able to reproduce on my end. It is wired because in theory lsp source will only attach to buffers with clients that supports `textDocument/documentSymbol` and will detach on `LspDetach` if no client that supports `textDocument/documentSymbol` attaches to the buffer.

https://github.com/Bekaboo/dropbar.nvim/blob/79309dccd5e5b94f9ddf5ee8587691d2bfea2858/lua/dropbar/sources/lsp.lua#L340

Additionally, please double check and do make sure that the default minimal config can reproduce this issue because there is no lsp set up in the minimal config.

A screen recording using the provided minimal config might help.

**Comment by miversen33** [comment] 2023-10-13 03:58
> @miversen33 Interesting, but I was not able to reproduce on my end. It is wired because in theory lsp source will only attach to buffers with clients that supports `textDocument/documentSymbol` and will detach on `LspDetach` if no client that supports `textDocument/documentSymbol` attaches to the buffer.
> 
> https://github.com/Bekaboo/dropbar.nvim/blob/79309dccd5e5b94f9ddf5ee8587691d2bfea2858/lua/dropbar/sources/lsp.lua#L340
> 
> Additionally, please double check and do make sure that the default minimal config can reproduce this issue because there is no lsp set up in the minimal config.
> 
> A screen recording using the provided minimal config might help.

I'll try again tomorrow and see if I can get you a recording of it :)

**Comment by miversen33** [comment] 2023-10-13 15:30
Well this is weird. So using the minimal configuration provided in the bug template, I am not able to recreate the issue. However if I just use dropbar in my existing configuration with _no_ configuration to dropbar, I see this issue crop up

https://github.com/Bekaboo/dropbar.nvim/assets/2640668/24b5b040-97dc-4c32-a9a0-171e845bd0b1


https://github.com/Bekaboo/dropbar.nvim/assets/2640668/bcc56338-4def-4a1e-ac07-cef9a0d50310

So this is most likely an issue with my configuration somehow conflicting with dropbar. Usually I would say its good to close out, but do you mind if we leave this open until I figure out what is wrong? I don't know that this issue is __actually__ dropbar related now, but given that the error does come from within dropbar, its possible there is some incompatiblity between dropbar and some other plugin I ma using which feels like something that should be uncovered and at least documented (if it exists at all and I am not just big dumb lol)

**Comment by Bekaboo** [comment] 2023-10-13 16:48
@miversen33 Looking at line 339 of `souces/lsp.lua`, there is a call to `vim.lsp.get_clients()`:

https://github.com/Bekaboo/dropbar.nvim/blob/79309dccd5e5b94f9ddf5ee8587691d2bfea2858/lua/dropbar/sources/lsp.lua#L339

the error is complaining that `vim.lsp.get_clients()` does not exist, but it is inside `vim.lsp` builtin lua module so it should always be available. Previously this was `vim.lsp.get_active_clients()` before `get_active_clients()` was deprecated, could it be the cause of the bug? Could you try using commit 3daffc1 or earlier versions?

**Comment by miversen33** [comment] 2023-10-13 18:20
> @miversen33 Looking at line 339 of `souces/lsp.lua`, there is a call to `vim.lsp.get_clients()`:
> 
> https://github.com/Bekaboo/dropbar.nvim/blob/79309dccd5e5b94f9ddf5ee8587691d2bfea2858/lua/dropbar/sources/lsp.lua#L339
> 
> the error is complaining that `vim.lsp.get_clients()` does not exist, but it is inside `vim.lsp` builtin lua module so it should always be available. Previously this was `vim.lsp.get_active_clients()` before `get_active_clients()` was deprecated, could it be the cause of the bug? Could you try using commit [3daffc1](https://github.com/Bekaboo/dropbar.nvim/commit/3daffc1215d715a4e9c544e2c71db16aab61d86f) or earlier versions?

I guess

> It's not me it's you

Reverting back to that commit makes the issue disappear

**Comment by Bekaboo** [comment] 2023-10-13 18:32
Good. Closing this issue.

**Closed by Bekaboo** 2023-10-13 18:32 UTC
Labels: bug

**Comment by miversen33** [comment] 2023-10-13 18:37
> Good. Closing this issue.

I'm a little bit confused though. So this means I am stuck on this specific commit right? Is this due to an incompatibility with the version of neovim I am currently using? Would changing my neovim version correct this issue? 

It sounds like the bug (and I think at this point it is fair to call it a bug) is due to calling a function that doesn't exist in vim.lsp (at least in my version of neovim). 

As I am using a nightly version, is the recommended solution to drop back to an older or newer nightly? Or back to 9.1 stable? I don't know that pinning to a specific commit of a plugin should be considered a solution?
