### ISSUE TITLE
[Feature]: update when back in normal mode only

### ISSUE THREAD

**Issue by gennaro-tedesco** [Bekaboo/dropbar.nvim#55] opened 2023-07-08 18:01 UTC
### Problem

Not really a problem, just a minor (personal) taste: whenever in insert mode, I see the upper dropbar flickering a little to update the portion of code I am writing and/or adding new elements. 

I see that the options
```lua
update_events = {
      buf = {
        'BufModifiedSet',
        'FileChangedShellPost',
        'TextChanged',
        'TextChangedI',
```
may control update events behaviour: I have tried removing `TextChangedI` and others but I see no difference. Is this the way to control the update behaviour or is my understanding wrong? Is it possible to have dropbar update only when back in normal mode (or, say, on `BufWritePost` or similar)?

### Expected behavior

An option to control update behaviours according to the mode you are in, in particular to only update when back in normal mode after editing.

**Comment by Bekaboo** [comment] 2023-07-08 18:18
Maybe try removing `CursorMovedI` too and please let me know if it works for you.

**Comment by gennaro-tedesco** [comment] 2023-07-08 18:27
I removed all events in `general.update_events` and the bar still updates in real time while in insert mode 🤔

**Comment by Bekaboo** [comment] 2023-07-08 18:36
How did you remove those events? If you do

```lua
dropbar.setup({
  general = {
    update_interval = 100,
    update_events = {}
  },
})
```

it won't work because the config table is deeply extended.

To disable all events you have to pass the config table like this:

```lua
dropbar.setup({
  general = {
    update_events = {
      win = {},
      buf = {},
      global = {},
    }
  },
})
```

**Comment by gennaro-tedesco** [comment] 2023-07-08 19:08
> To disable all events you have to pass the config table like this:

yes, I did so but it still updates in real time. Do you see a different behaviour? I am using the minimal configuration
```lua
dropbar.setup({
  general = {
    update_events = {
      win = {},
      buf = {},
      global = {},
    }
  },
})
```
on 
```
NVIM v0.10.0-dev-653+gfbeef0d4e-Homebrew
Build type: Release
LuaJIT 2.1.0-beta3
```
Could you not reproduce it?

**Comment by theofabilous** [comment] 2023-07-08 20:37
@gennaro-tedesco I can reproduce this. I think [these lines in `sources.lsp`](https://github.com/Bekaboo/dropbar.nvim/blob/19cd4d1ad17562bec2b7d4861f47ff69d9f2e5ba/lua/dropbar/sources/lsp.lua#L308-L315) are related.

Try running:
```lua
vim.api.nvim_clear_autocmds({ group = 'DropBarLsp', event = 'TextChangedI' })
```
and if you have [nvim-cmp](https://github.com/hrsh7th/nvim-cmp), also run:
```lua
vim.api.nvim_clear_autocmds({ group = '___cmp___', event = 'TextChangedI' })
```
Does it still update after clearing those augroups? Note that this isn't a fix, both these commands likely break functionality.

**Comment by Bekaboo** [comment] 2023-07-08 20:48
@gennaro-tedesco Should be fixed in latest commit on `master`.

**Closed** 2023-07-08 20:47 UTC
Labels: enhancement

**Comment by gennaro-tedesco** [comment] 2023-07-08 21:58
What is the correct way to define the relevant options now, namely what events should or should not be specified?

**Comment by Bekaboo** [comment] 2023-07-08 22:01
@gennaro-tedesco Previously `lsp` source will request a winbar update on `TextChanged` and `TextChangedI` which is independent from update events. In the latest version if you want to disable updates on events `TextChangedI` and `CursorMovedI` simply removing them in the config table should be fine.

**Comment by gennaro-tedesco** [comment] 2023-07-08 22:17
I confirm it works as expected, thank you very much for reacting so quickly!
