### ISSUE TITLE
[Bug]: Dropdown closes immediately after badge selection

### ISSUE THREAD

**Issue by jla2000** [Bekaboo/dropbar.nvim#85] opened 2023-09-06 17:38 UTC
### Description

I'm using LazyVim 6.3.0 as the base and I just added to dropbar plugin to it.
When trying to select from the dropbar lua `require("dropbar.api").pick()` it shows the alphabetic letters to choose the badge for selection, but when selecting one the dropdown appears for just a small fraction and disappears, so I'm not able to select anything from there. When selecting with the mouse it works fine tho.

### nvim version

v0.10.0-dev-1031+gc431d820e

### dropbar.nvim version

d9e2b240e9d4fe42fc74c9e40127f3217f00e14b

### Operating system and version

MacOS Ventura 13.5.1

### Minimal config

```Lua
local lazypath = vim.fn.stdpath("data") .. "/lazy/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({
		"git",
		"clone",
		"--filter=blob:none",
		"https://github.com/folke/lazy.nvim.git",
		"--branch=stable", -- latest stable release
		lazypath,
	})
end
vim.opt.rtp:prepend(lazypath)

require("lazy").setup({
	{
		"Bekaboo/dropbar.nvim",
	},
})

```

### Steps to reproduce

Add the plugin via lazy and try to select using the pick function

### Expected behavior

Dropdown appears and items can be selected

### Actual behavior

Dropdown disappears after one blink

**Comment by jla2000** [comment] 2023-09-07 12:04
@Bekaboo
I added an minimal config. I think the problem originates from lazy loading the plugin.

**Comment by jla2000** [comment] 2023-09-07 12:53
It works just fine when directly opening a file after the plugin has been installed by lazy, and after closing nvim it doesnt work anymore. Deleting ~/.local/state/nvim does restore functionality for the next nvim run, after closing it it again doesnt work anymore

**Comment by Bekaboo** [comment] 2023-09-07 18:07
@jla2000 Cannot reproduce. I'm using nvim compiled from commit `c431d820e`, same as the version in your bug report.

![repro](https://github.com/Bekaboo/dropbar.nvim/assets/76579810/bb3c99ef-1dd7-4a3e-9d45-ae8772827edf)

**Comment by jla2000** [comment] 2023-09-08 07:10
@Bekaboo This is how it looks for me:
![dropbar](https://github.com/Bekaboo/dropbar.nvim/assets/138496837/82fd02d8-1ea0-459a-b0f3-db0a2ff5b0f6)

**Comment by Bekaboo** [comment] 2023-09-08 08:18
@jla2000 Cannot reproduce. Make sure you don't have any custom auto commands around.

![repro](https://github.com/Bekaboo/dropbar.nvim/assets/76579810/dc713abb-768a-44af-9917-2326ffe4630e)

**Comment by jla2000** [comment] 2023-09-08 11:38
@Bekaboo 
Could it be that is has something to do with this init.net.lua you're showing?
For me this behaviour with the posted init.lua is completely reproducable, its the same bug on my windows laptop as well as on my Macbook Air.

**Comment by jla2000** [comment] 2023-09-08 11:42
> Make sure you don't have any custom auto commands around.
> 

I'm just using there vanilla neovim with no other file configured than the posted config 🙃

**Comment by Bekaboo** [comment] 2023-09-08 11:46
> Could it be that is has something to do with this init.net.lua you're showing?

No, it is not sourced.

> I'm just using there vanilla neovim with no other file configured than the posted config 🙃

Considering you are the only one that has this issue and it is not reproducible on my end, it is more likely that there are something special happening on your neovim installation or device.

**Comment by Bekaboo** [comment] 2023-09-08 11:48
Closing, cannot reproduce.

**Closed by Bekaboo** 2023-09-08 11:48 UTC
Labels: bug
