### ISSUE TITLE
[Bug]: Dropbar crashing after update to 4.0.0

### ISSUE THREAD

**Issue by borisbsv** [Bekaboo/dropbar.nvim#50] opened 2023-07-07 08:21 UTC
### Description

After updating the pinned version to `v4.0.0` and running `PackerUpdate` dropbar crashes with the following message:

```lua
E5108: Error executing lua .../site/pack/packer/start/dropbar.nvim/lua/dropbar/bar.lua:459: attempt to index field 'uv' (a 
nil value)                                                                                                                 
stack traceback:                                                                                                           
        .../site/pack/packer/start/dropbar.nvim/lua/dropbar/bar.lua:459: in function 'update'                              
        .../site/pack/packer/start/dropbar.nvim/lua/dropbar/bar.lua:658: in function <.../site/pack/packer/start/dropbar.nv
im/lua/dropbar/bar.lua:656>
```

### nvim version

 nvim --version NVIM v0.10.0-dev-416+g70da793c5-Homebrew Build type: Release LuaJIT 2.1.0-beta3     system vimrc file: "$VIM/sysinit.vim"   fall-back for $VIM: "/opt/homebrew/Cellar/neovim/HEAD-70da793/share/nvim"

### dropbar.nvim version

8b18a1f

### Operating system and version

macOS 13.4.1

### Minimal config

```Lua
local tmp = vim.env.TMPDIR
  or vim.env.TEMPDIR
  or vim.env.TMP
  or vim.env.TEMP
  or '/tmp'
local data = tmp ..  '/' .. (vim.env.NVIM_APPNAME or 'nvim')
local packages_root = data .. '/site'
local cloned_root = packages_root .. '/pack/packages/start'
local cloned_path = cloned_root .. '/dropbar.nvim'
local url = 'https://github.com/Bekaboo/dropbar.nvim.git'

vim.fn.mkdir(cloned_root, 'p')
vim.opt.pp:prepend(packages_root)
vim.opt.rtp:prepend(packages_root)

if not vim.loop.fs_stat(cloned_path) then
  vim.fn.system({ 'git', 'clone', url, cloned_path })
end

require('dropbar').setup()
```

### Steps to reproduce

1. try opening any file in a buffer `:e <filepath`

### Expected behavior

The file opens and dropbar initializes.

### Actual behavior

```lua
E5108: Error executing lua ...ite/pack/packages/start/dropbar.nvim/lua/dropbar/bar.lua:463: attempt to index field 'uv' (a 
nil value)
stack traceback:
        ...ite/pack/packages/start/dropbar.nvim/lua/dropbar/bar.lua:463: in function 'update'
        ...ite/pack/packages/start/dropbar.nvim/lua/dropbar/bar.lua:699: in function <...ite/pack/packages/start/dropbar.nv
im/lua/dropbar/bar.lua:697>
```
The error above appears in messages and keeps appearing every time I interact with nvim.

**Comment by Bekaboo** [comment] 2023-07-07 08:33
Duplicate of #44

**Closed by Bekaboo** 2023-07-07 08:33 UTC
Labels: bug
