### ISSUE TITLE
[Bug]: DropBarMenuFloatBorder highlight doesn't seems to have any effect

### ISSUE THREAD

**Issue by jaymorelli96** [Bekaboo/dropbar.nvim#187] opened 2024-10-15 16:24 UTC
### Description

Not sure if I am doing this correctly but no matter what I set the highlight for the floatborder doesn't work, only the DropBarMenuNormalFloat seems to have an impact. I would like to add border in the dropdown menu, is it possible?

### nvim version

v0.10.1

### dropbar.nvim version

35988affc74c0cebb1484bcdfccfed523c0e7267

### Operating system and version

Manjaro 

### Minimal config

```Lua
return {
  'Bekaboo/dropbar.nvim',
  -- optional, but required for fuzzy finder support
  dependencies = {
    'nvim-telescope/telescope-fzf-native.nvim',
  },
  config = function()
    -- Load the dropbar picker API
    local dropbar_picker = require 'dropbar.api' -- change from 'ai' to 'api'

    -- Set keymap to call dropbar_picker.pick() when <leader>d is pressed
    vim.keymap.set('n', ' d', dropbar_picker.pick, { desc = '[D]ropbar Picker' })
  end,
  opts = {
    menu = {
      win_configs = {
        border = 'string',
        width = 2,
      },
    },
  },
}

vim.api.nvim_set_hl(0, 'DropBarMenuNormalFloat', { bg = '#3b4252' })
vim.api.nvim_set_hl(0, 'DropBarMenuFloatBorder', { bg = '#2e3440', fg = '#5e81ac' }) -- testing colors
```

### Steps to reproduce

1. Use the same config for the dropbar
2. Set highlight color for float border

### Expected behavior

Display border in dropdown menu

### Actual behavior

No border is displayed

**Comment by Bekaboo** [comment] 2024-10-24 05:22
Hi, thanks for the bug report. Please use the provided minimal config instead of the current one when reporting bugs, it makes my life easier.

There is an error in your `opts` -- `border` cannot be set to `"string"`, for possible values of `border`, please refer to `:h nvim_open_win`. In addition, I noticed that you set the width of the menu window to 2, which is way too small in most cases, why are you doing so?

If you want to, for example, set the border with red background and green foreground, try the following:

```lua
require('dropbar').setup({
  menu = {
    win_configs = {
      border = 'single',
    },
  },
})

vim.api.nvim_set_hl(
  0,
  'DropBarMenuFloatBorder',
  { bg = '#ff0000', fg = '#00ff00' }
)
```

**Comment by Bekaboo** [comment] 2024-10-24 05:24
Closing -- not a bug and cannot reproduce. Feel free to reopen if you have further questions.

**Closed by Bekaboo** 2024-10-24 05:24 UTC
Labels: bug

**Comment by jaymorelli96** [comment] 2024-10-25 15:47
Hi @Bekaboo, actually my problem was that I was using the `opts` table instead of setup... Sorry and thanks for the help!

**Comment by Bekaboo** [comment] 2024-10-25 16:01
If you are using lazy.nvim package manager, it should be fine using `opts`, it calls `setup()` under the hood. Glad that you've solved the problem!

**Comment by jaymorelli96** [comment] 2024-10-25 16:17
Yeah that is what I thought 🤔  Not sure why that happened to me, but maybe it will be useful information for other in the future.

Anyway, thanks for this great plugin!
